"""Refresh what the docs plot: the chart page's numbers, and the SVG figures.

    uv run python -m bench.plot

Two outputs from one read of the results, so a page and a figure can never
disagree about the same run. ``docs/charts/*.svg`` are what
``docs/benchmarks.md`` embeds — see :mod:`bench.svg` for why they are committed
files rather than something drawn at view time.

The page is a tracked source file, not a build artifact: its markup, prose and
renderer are edited by hand and reviewed in the diff. Only the measurements go
stale, so this rewrites exactly one line of it — the ``const DATA = {...};``
literal — and touches nothing else. Templating the page instead would move the
interesting part (what the bands *say*) into a file nobody opens.

Two result files, because the page plots two runs: the ladder (six models to
`l`, through the `highs` sink) and the scaling run (`dispatch` alone out to
120M, through `lp`). A rung either run is missing stops this rather than
drawing a line that skips it, which would read as a measurement.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

from bench import results as bench_results

NAME = {'lpspec': 'polars', 'linopy': 'linopy'}
LADDER = ('xs', 's', 'm', 'l')
SCALING = ('xs', 's', 'm', 'l', 'xl', '2xl')
_DATA = re.compile(r'^const DATA = .*;$', re.MULTILINE)


def measurements(name: str) -> Path:
    """The results file called *name*, in whichever format is committed.

    The harness writes `.json` now; `bench/results/` still holds the `.jsonl`
    the previous one wrote. Preferring the new and falling back to the old is
    what lets this run against the tree as it stands rather than only after
    the next full ladder.
    """
    for suffix in ('.json', '.jsonl'):
        path = Path('bench/results') / f'{name}{suffix}'
        if path.exists():
            return path
    raise SystemExit(f'no bench/results/{name}.json — run the ladder first (bench/README.md)')


def best(path: Path, sink: str) -> dict[str, dict[Any, Any]]:
    """``(case, size, arm) -> fastest repeat``. Minimum, because noise only adds."""
    out: dict[str, dict[Any, Any]] = {'wall': {}, 'peak': {}, 'cols': {}}
    for r in bench_results.records(path):
        if r.get('record') != 'timing' or 'error' in r or r.get('sink') != sink:
            continue
        k = (r['case'], r['size'], r['arm'])
        out['wall'][k] = min(out['wall'].get(k, 9e99), r['wall_seconds'])
        out['peak'][k] = min(out['peak'].get(k, 9e99), r['peak_rss_bytes'] / 1e9)
        out['cols'][(r['case'], r['size'])] = r['counts']['columns']
    return out


def _at(table: dict[Any, Any], key: Any) -> Any:
    if key not in table:
        raise SystemExit(f'no measurement for {key} — the page plots that point, so the run has to cover it')
    return table[key]


def panel(t: dict[str, dict[Any, Any]], case: str, rungs: tuple[str, ...], arms: tuple[str, ...]) -> dict[str, Any]:
    return {
        'vars': [_at(t['cols'], (case, r)) for r in rungs],
        **{m: {NAME[a]: [round(_at(t[m], (case, r, a)), 3) for r in rungs] for a in arms} for m in ('wall', 'peak')},
    }


#: Which sinks the figures face. A sink absent from the results is dropped
#: rather than drawn empty — a facet with no line reads as a measurement of
#: zero, and a reader has no way to tell it from one.
SINKS = ('highs', 'lp', 'gurobi')


def figures(results: Path) -> list[tuple[str, Any]]:
    """The figures `docs/benchmarks.md` embeds, as (name, builder) pairs."""
    from bench import svg

    stamp = f'generated by bench.plot from {results.name}'
    per_sink = {s: best(results, s) for s in SINKS}
    present = [s for s in SINKS if per_sink[s]['wall']]

    def lines(metric: str, unit: str, label: str, caption: str) -> svg.Figure:
        panels = []
        for sink in present:
            table = per_sink[sink]
            panels.append(
                svg.Panel(
                    title=f'{sink} sink',
                    series=[
                        svg.Series(
                            NAME[arm],
                            [
                                (_at(table['cols'], ('dispatch', r)), _at(table[metric], ('dispatch', r, arm)))
                                for r in LADDER
                            ],
                            slot=i,
                        )
                        for i, arm in enumerate(('lpspec', 'linopy'))
                    ],
                )
            )
        return svg.Figure(
            panels=panels,
            x_label='variables in the model',
            y_label=label,
            y_unit=unit,
            caption=caption,
            provenance=stamp,
        )

    def cases(scheme: svg.Scheme) -> str:
        table = per_sink['highs']
        names = sorted({c for c, _, _ in table['wall']})
        panels = [
            svg.Panel(
                title=name,
                series=[
                    svg.Series(
                        NAME[arm],
                        [(_at(table['cols'], (name, r)), _at(table['wall'], (name, r, arm))) for r in LADDER],
                        slot=i,
                    )
                    for i, arm in enumerate(('lpspec', 'linopy'))
                ],
            )
            for name in names
        ]
        return svg.render(
            svg.Figure(
                panels=panels,
                x_label='variables in the model',
                y_label='wall seconds',
                caption='Every model in the corpus, through the highs sink. Same two lines, same order, six shapes.',
                provenance=stamp,
                width=1180,
                panel_height=190,
            ),
            scheme,
        )

    def phases(scheme: svg.Scheme) -> str:
        wanted = [
            r
            for r in bench_results.records(results)
            if r.get('record') == 'timing' and r.get('sink') == 'highs' and r.get('size') == 'l' and 'error' not in r
        ]
        # teardown is ~10us at every rung: a legend entry for a segment that
        # never draws is noise, and `import` is excluded as the tables exclude it
        order = ('build', 'emit')
        groups = []
        for case in sorted({r['case'] for r in wanted}):
            arms = []
            for arm in ('lpspec', 'linopy'):
                best_run = min(
                    (r for r in wanted if r['case'] == case and r['arm'] == arm),
                    key=lambda r: r['wall_seconds'],
                    default=None,
                )
                if best_run:
                    arms.append((NAME[arm], [(p, best_run['phases'].get(p, 0.0)) for p in order]))
            if arms:
                groups.append((case, arms))
        return svg.bars(
            groups,
            order,
            scheme,
            caption='Where the time goes at the `l` rung — import excluded, it is paid once per process.',
            provenance=stamp,
        )

    return [
        ('wall', lines('wall', 's', 'wall seconds', 'Wall time to a loaded solver. Both axes are log.')),
        ('peak', lines('peak', 'GB', 'peak RSS (GB)', 'Peak resident memory for the same builds. Both axes are log.')),
        ('cases', cases),
        ('phases', phases),
    ]


def main() -> int:
    ladder = best(measurements('latest'), 'highs')
    scaling = best(measurements('scaling'), 'lp')
    cases = sorted({c for c, _, _ in ladder['wall']})
    data = {
        'scaling': panel(scaling, 'dispatch', SCALING, ('lpspec', 'linopy')),
        'cases': {c: panel(ladder, c, LADDER, ('lpspec', 'linopy')) for c in cases},
        'caseNames': cases,
        'rungs': list(LADDER),
    }

    page = Path('docs/benchmarks-scaling.html')
    text = page.read_text()
    if not _DATA.search(text):
        raise SystemExit(f'{page} has no `const DATA = ...;` line — keep the literal on one line of its own')
    page.write_text(_DATA.sub(lambda _: 'const DATA = ' + json.dumps(data) + ';', text, count=1))
    print(f'{page} refreshed')

    from bench import svg

    written = svg.write(figures(measurements('latest')), 'docs/charts')
    print(f'{len(written)} figures -> docs/charts/')
    return 0


if __name__ == '__main__':
    sys.exit(main())
